// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-O3vd5BJ85kSokoOXs1vS0CNyi3jChI8',
    appId: '1:21002965049:android:5bf064638368eb4a0f7de8',
    messagingSenderId: '21002965049',
    projectId: 'first-4cbb3',
    storageBucket: 'first-4cbb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeyp_5I7Bvh1gihhZYYm2U4hMUaoSIkKQ',
    appId: '1:21002965049:ios:81bba827e2ad831b0f7de8',
    messagingSenderId: '21002965049',
    projectId: 'first-4cbb3',
    storageBucket: 'first-4cbb3.appspot.com',
    iosClientId: '21002965049-ercg37rf5717ls36sdoqc0r9ecl7d1m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeyp_5I7Bvh1gihhZYYm2U4hMUaoSIkKQ',
    appId: '1:21002965049:ios:81bba827e2ad831b0f7de8',
    messagingSenderId: '21002965049',
    projectId: 'first-4cbb3',
    storageBucket: 'first-4cbb3.appspot.com',
    iosClientId: '21002965049-ercg37rf5717ls36sdoqc0r9ecl7d1m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseproject',
  );
}
